### ISSUE TITLE
Open Starting Page in Jupyter session per default

### ISSUE THREAD

**Issue by tkilias** [exasol/data-science-sandbox#137]
When a Jupyter Lab session is started in the web browser, we want that the user directly sees the starting page.

There are few ways how this should work:

- [workspaces](https://jupyterlab.readthedocs.io/en/stable/user/urls.html#managing-workspaces-cli)
  - I didn't get this reliable to work
- jupyter-lab  <notebook-file>
  - seems to work only for the first login
- [File navigation with tree URL](https://jupyterlab.readthedocs.io/en/stable/user/urls.html#file-navigation-with-tree)
  - this seems to work reliable, in that case we need to adjust the URL we show the user to connect to
 

### Acceptance criteria

The URL currently is `http://<host>:<forwarded port>/lab/tree/start.ipynb`

* `runtime/ansible/roles/jupyter/tasks/jupyterlab.yml` is updated to set the URL as default URL in Juypter lab config 
see https://jupyterlab-server.readthedocs.io/en/latest/api/app-config.html

```
c.LabApp.default_url = '/lab/tree/start.ipynb'
```
![image](https://github.com/exasol/data-science-sandbox/assets/81821845/62a04567-1c0b-4cb1-abce-b5ed65cd01db)

* motd is updated to show connection URL for AMI and VM Editions
* User guide is updated to **not use** `--detach` to ensure the boot message is displayed directly without needing to use `docker logs`
* The following documents and scripts display the correct URL
  * entrypoint (derived from ansible)
  * [User Guide](https://github.com/exasol/data-science-sandbox/blob/main/doc/user_guide/user_guide.md#connecting-to-jupyter-service)
  * [Docker Usage](https://github.com/exasol/data-science-sandbox/blob/main/doc/user_guide/docker/docker_usage.md#enable-ai-lab-to-access-the-docker-daemon) as this might be a little bit more specific

**Comment by ckunki** [comment]
Ir order to show the URL to users I see multiple places affected: 
* The message when starting the docker container from command line 
  * Additionally we could change the start command to **not use** `--detach` to ensure the message is displayed immediately and does not require to use `docker logs`
* [User Guide](https://github.com/exasol/data-science-sandbox/blob/main/doc/user_guide/user_guide.md#connecting-to-jupyter-service)
* [Docker Usage](https://github.com/exasol/data-science-sandbox/blob/main/doc/user_guide/docker/docker_usage.md#enable-ai-lab-to-access-the-docker-daemon) as this might be a little bit more specific?

**Comment by ckunki** [comment]
Please add the URL to the current ticket.

**Comment by ckunki** [comment]
Proposal: `http://<host>:<forwarded port>/lab/tree/start.ipynb`

**Comment by tkilias** [comment]
@ckunki I think, we also need to change the motd for the VMs

**Comment by tkilias** [comment]
@ckunki and we should set the defaul_url in the jupyterlab config https://jupyterlab-server.readthedocs.io/en/latest/api/app-config.html
