### ISSUE TITLE
Remove apt cache to reduces image size

### ISSUE THREAD

**Issue by tkilias** [exasol/data-science-sandbox#67]
Background

We need to update the apt cache during the setup of the EC-2 instance. Maybe we could decrease the size of the final VM files by cleaning up the apt cache at the end.
Acceptance Criteria

Run:

- ansible.builtin.apt:
    clean: yes
  become: yes

-  ansible.builtin.file:
   path: /var/lib/apt/lists/
   state: absent

at the end of the setup

See also https://askubuntu.com/questions/1050800/how-do-i-remove-the-apt-package-index

Here a measurement on our image

```
$ docker run -it exasol/data-science-sandbox:0.1.0-dev-1 bash
root@9fed5334f0a2:/# du -sh  /var/lib/apt/lists/
46M	/var/lib/apt/lists/
```

**Comment by ckunki** [comment]
Alternatively we could check `sudo rm -rf /var/lib/apt/lists/*`

**Comment by ckunki** [comment]
For `ansible.builtin.apt` option `become: yes` seems to not be supported.

**Comment by ckunki** [comment]
- Before: Built Docker image exasol/data-science-sandbox:0.1.0 size 193.95 MB in 0:00:30. 
- After: Built Docker image exasol/data-science-sandbox:0.1.0 size 178.19 MB in 0:00:39.

**Comment by tkilias** [comment]
> For `ansible.builtin.apt` option `become: yes` seems to not be supported.
> 
> > fatal: [ds-sandbox-1700486283]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.builtin.apt) module: become.
> 
> Supported parameters include:
> 
>     * force
> 
>     * clean
> 
>     * allow_downgrade (allow-downgrade, allow-downgrades, allow_downgrades),
> 
>     * allow_change_held_packages
> 
>     * purge
> 
>     * install_recommends (install-recommends)
> 
>     * policy_rc_d
> 
>     * cache_valid_time
> 
>     * package (name, pkg)
> 
>     * update_cache (update-cache)
> 
>     * update_cache_retry_max_delay
> 
>     * force_apt_get
> 
>     * only_upgrade
> 
>     * fail_on_autoremove
> 
>     * lock_timeout
> 
>     * default_release (default-release)
> 
>     * upgrade
> 
>     * update_cache_retries
> 
>     * allow_unauthenticated (allow-unauthenticated)
> 
>     * deb
> 
>     * dpkg_options
> 
>     * state
> 
>     * autoremove
> 
>     * autoclean

@ckunki This seems to be an indentation issue, because `become` is not a parameter of the command, but of the general task definition.

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#become-directives
